site_name: Taller Game Boy
site_url: https://makeclassicgames.dev/tallergbstudio/
site_description: Taller de desarrollo de juegos para Game Boy y Game Boy Color impartido en la Euskal Encounter 2026 por el canal de YouTube y Twitch "Make Classic Games".
site_author: Make Classic Games
site_copyright: Make Classic Games
site_keywords: Game Boy, Game Boy Color, gbstudio, desarrollo de juegos, tutoriales, recursos, sprites, tilesets, música, sonido, programación, videojuegos retro
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: Roboto Mono
    code: Roboto Mono
  features:

    - search.highlight
    - search.suggest
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - Game Boy:
    - Game Boy: gameboy.md
    - Game Boy Color: gameboycolor.md
  - Desarrollo para Game Boy:
    - Desarrollo para Game Boy: desarrollo_game_boy.md
    - GBStudio: gbstudio.md
    - Primeros pasos con GBStudio: primeros_pasos_gbstudio.md
  - Juego para Game Boy:
    - Introducción: juego/introduccion.md
    - Primera Escena: juego/primera_escena.md
    - Fondos: juego/fondos.md
    - Sprites y Animaciones: juego/sprites_animaciones.md
    - Actores: juego/actores_sprites.md
    - Acciones (Eventos): juego/acciones_eventos.md
    - Más Acciones y Escenas: juego/mas_acciones_escenas.md
    - Música y Sonido: juego/musica_sonido.md
    - Publicación del juego: juego/publicacion_juego.md
  - Referencias: referencias.md
extra:
    social:
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/@makeclassicgames
      - icon: fontawesome/brands/twitch
        link: https://www.twitch.tv/makeclassicgames
copyright: Copyright &copy; 2026 Make Classic Games. Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.